language: bash
sudo: required
dist: trusty

notifications:
    email: false

script:
    - ./install-julia.sh
    - ./install-julia.sh release-0.3
    - . ~/.bashrc
    - julia-release-0.4 test/simple.jl
    - julia-release-0.3 test/simple.jl
